### ISSUE TITLE
attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ChenyangRan** [youngwoon/robot-learning#1]
First of all, thanks for your work. I meet some trouble using your master-branch.
I type the following command, and the errror is ``` attempted relative import with no known parent package```
```
python -m run --run_prefix test --algo ppo --env "Hopper-v2"
```
![image](https://user-images.githubusercontent.com/29306735/96978585-1859ba80-1551-11eb-94f2-018f87a95cb2.png)

I have searched online but they don't work.
Could you please help me?
I just clone your code and install the requirements.txt on Ubuntu 16.04.
I have tested the python 3.6 and 3.7.

**Comment by ChenyangRan** [comment]
By the way, could you please tell me how to train the agent in dm_control?

**Comment by youngwoon** [comment]
Hi, the current code has an issue with running inside the directory. 
I'm now using it as a sub-module in other projects.

So, simply make a parent directory and make `run.py` inside the parent directory as follows:

- `parent`
  - `run.py`
  - `method` <- robot-learning repo

```
# run.py
from method.main import run
from method.config import create_parser


if __name__ == "__main__":
    # default arguments
    parser = create_parser()

    # change default values
    parser.set_defaults(wandb_project="my_project")

    # execute training code in method/main.py
    run(parser)
```

**Comment by ChenyangRan** [comment]
> 
> 
> Hi, the current code has an issue with running inside the directory.
> I'm now using it as a sub-module in other projects.
> 
> So, simply make a parent directory and make `run.py` inside the parent directory as follows:
> 
>     * `parent`
>       
>       * `run.py`
>       * `method` <- robot-learning repo
> 
> 
> ```
> # run.py
> from method.main import run
> from method.config import create_parser
> 
> 
> if __name__ == "__main__":
>     # default arguments
>     parser = create_parser()
> 
>     # change default values
>     parser.set_defaults(wandb_project="my_project")
> 
>     # execute training code in method/main.py
>     run(parser)
> ```

Thanks for your replay. It works well !
